"""Ajout du nom de fichier pour la publication

Revision ID: 169fac0fc8dd
Revises: 63523858a758
Create Date: 2025-08-12 00:48:04.090102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169fac0fc8dd'
down_revision = '63523858a758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('published_filename')

    # ### end Alembic commands ###
