"""Add client_published_filename to Trip

Revision ID: 285c37d40279
Revises: 169fac0fc8dd
Create Date: 2025-08-12 22:27:41.284507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285c37d40279'
down_revision = '169fac0fc8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_published_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('client_published_filename')

    # ### end Alembic commands ###
