"""Initial migration

Revision ID: 63523858a758
Revises: 
Create Date: 2025-08-11 21:14:55.546901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63523858a758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_data_json', sa.Text(), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('client_first_name', sa.String(length=100), nullable=True),
    sa.Column('client_last_name', sa.String(length=100), nullable=True),
    sa.Column('client_email', sa.String(length=120), nullable=True),
    sa.Column('stripe_payment_link', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
