"""add document_filenames to trip

Revision ID: 823c3a7a83cb
Revises: 285c37d40279
Create Date: 2025-10-02 11:15:11.510261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823c3a7a83cb'
down_revision = '285c37d40279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ultra_budget', sa.Boolean(), server_default='f', nullable=False))
        batch_op.add_column(sa.Column('client_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('down_payment_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('balance_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('document_filenames', sa.Text(), nullable=True))
        batch_op.alter_column('stripe_payment_link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('stripe_payment_link',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('document_filenames')
        batch_op.drop_column('balance_due_date')
        batch_op.drop_column('down_payment_amount')
        batch_op.drop_column('client_phone')
        batch_op.drop_column('is_ultra_budget')

    # ### end Alembic commands ###
